# Generated by Django 3.2.12 on 2023-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tzname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='usertimezone',
            name='timeZone',
            field=models.CharField(default='UTC', max_length=30),
        ),
    ]
